/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.task_1;

/**
 *
 * @author Lenovo
 */
import java.util.*;
public class Task_1 {
    public static void main(String[] args) {
        System.out.println("NUMBER GAME");
        System.out.println("----------------------------------------");
         Random r=new Random();
         int rand=r.nextInt(101);
        int attempts=0;
        int attempts_allowed=3;
      System.out.println("A random number is generated by the computer");
      System.out.println("You have to enter your guess for the generated number");
      
 while(attempts<3 & attempts_allowed>0){
     System.out.println();
     System.out.print("Enter a number between 1 to 100: ");
      Scanner s=new Scanner(System.in);
      int num=s.nextInt();
    if(num<rand){
        System.out.println("Your number is lesser than the random number");  
    } 
     
    if(num>rand & num<101){
        System.out.println("Youe number is greater than the random number");
         
    }
    
    if(num>100){
        System.out.println("INVALID NUMBER!!!! Please try again"); 
    }
   
    if(num==rand){
        System.out.println("Bravo!!! Your guessed the correct number");
      break;
    }
    attempts++;
    attempts_allowed--;
 }  
 System.out.println();
 if(attempts==3){
     System.out.println("Sorry!!! Your attempts are finished....Try again");
 }
 System.out.println();
     System.out.println("The random number generated was: "+rand);
    }}